version: "3.8"

services:
  hello:
    image: alpine
    container_name: hello-world-container
    command: echo "Hello, $GREETING_TARGET!"
    environment:
      - GREETING_TARGET=${GREETING_TARGET}
      - Var-run=$RUNNER
