name: New build Conditional Docker Build on Self-hosted Runners

on:
  push:
    branches:
      - main

jobs:
  choose-runner:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    outputs:
      target-runner: ${{ steps.set-runner.outputs.target-runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read var-run from docker-compose.yml
        id: read-var
        run: |
          VAR_RUN=$(grep 'var-run=' docker-compose.yml | cut -d '=' -f2 | tr -d '[:space:]')
          echo "var_run=$VAR_RUN" >> $GITHUB_OUTPUT

      - name: Set runner label based on var-run
        id: set-runner
        env:
          VAR_RUN: ${{ steps.read-var.outputs.var_run }}
        run: |
          if [ "$VAR_RUN" = "runner1" ]; then
            echo "target-runner=self-hosted,runner-new-1" >> $GITHUB_OUTPUT
            ls
            pwd
          elif [ "$VAR_RUN" = "runner2" ]; then
            echo "target-runner=self-hosted,runner-new-2" >> $GITHUB_OUTPUT
            ls
            pwd
          else
            echo "Invalid var-run: $VAR_RUN"
            exit 1
