  stages:
     - build

# Джоб для runner-new-1
  build-runner-1:
  stage: build
  script:
    - echo "Компиляция на runner-new-1"
    - make build  # или ваша команда сборки
  tags:
    - runner-new-1
  rules:
    - if: '$Var_run == "runner1"'
      when: always
    - when: never

# Джоб для runner-new-2
build-runner-2:
  stage: build
  script:
    - echo "Компиляция на runner-new-2"
    - make build  # или ваша команда сборки
  tags:
    - runner-new-2
  rules:
    - if: '$Var_run == "runner2"'
      when: always
    - when: never
