name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      Var_run:
        description: "Выбор раннера"
        required: true
        default: "runner1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Сборка на runner-new-1
        if: ${{ github.event_name == 'push' || github.event.inputs.Var_run == 'runner1' }}
        run: |
          echo "Сборка на runner-new-1"
          # Здесь может быть ваша реальная команда сборки

      - name: Сборка на runner-new-2
        if: ${{ github.event.inputs.Var_run == 'runner2' }}
        run: |
          echo "Сборка на runner-new-2"
