name: BlazorApp

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'BlazorApp/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'BlazorApp/**'
      
jobs:
  build:

   runs-on: self-hosted
   steps:
  # Build the Docker image
   - name: Build BlazorApp
     run: |-
         docker images | grep "<none>" | awk '{print $3}'| xargs --no-run-if-empty docker rmi
