name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
      - name: Get current time
        id: time
#        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        run: echo "::set-output name=date::$(date -d "+5 hours" +'%H:%m')"

      - name: Get telegram id
        id: tgid
        run: | 
          if [[ ${{ steps.time.outputs.date }} > 15:00 ]]; then
           ${{ TELEGRAM_ID }} = ${{ secrets.TELEGRAM_TO }}
           echo Vari 1
          else
           ${{ TELEGRAM_ID }} = ${{ secrets.TGUSER1 }}
           echo Vari 3
          fi
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ TELEGRAM_ID }}
#          to: $ {{ secrets.TGUSER1 }}
          
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Current time: ${{ steps.time.outputs.date }}
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
