name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
#    env:
#     chat_id: 498741460
#     test_message: 1234
     
    steps:
#      - name: echo env
#        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
#        run: echo $chat_id
     
#      - name: Get current time
#        id: time
#        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
#        run: echo "::set-output name=date::$(date -d "+5 hours" +'%H:%m')"

      - name: Get telegram id
        id: tgid
#        env:
#        test_message: 1234
        run: | 
          declare -A DICTIONARY
          DICTIONARY["key1"]="498741460"
          DICTIONARY["key2"]="1235433753"
          DICTIONARY["key3"]="value3"

          if [[ ${{ github.actor }} == "Artidv1" ]]; then
            SELECTED=${DICTIONARY["key1"]}
          else
            SELECTED=${DICTIONARY["key2"]}
          fi
          echo "SELECTED=$SELECTED" >> $GITHUB_ENV
          echo $SELECTED
      - name: send telegram message on push
        id: tgsend
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
#          to: ${{ env.chat_id }}
          to: ${{ env.SELECTED }}
       
          
#          to: $ {{ secrets.TGUSER1 }}
          
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Current time: ${{ steps.time.outputs.date }}
            Repository: ${{ github.repository }}
            Telegram id is: ${{ $SELECTED }}
                       See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
